@startuml DonaTrack_Despliegue

skinparam backgroundColor #FFFFFF
skinparam nodesep 60
skinparam ranksep 70
skinparam node {
 BackgroundColor #EEEDFE
 BorderColor #7F77DD
 FontColor #000000
}
skinparam artifact {
 BackgroundColor #E1F5EE
 BorderColor #7F77DD
 FontColor #000000
}
skinparam database {
 BackgroundColor #FAEEDA
 BorderColor #BA7517
 FontColor #000000
}

node "Cliente\n(administrador / entidad)" as nCliente {
 artifact "donantes.csv" as csv
 artifact "Web Browser\n(dashboard de monitoreo)" as browser
}

node "Celular del chofer" as nCelular {
 artifact "App móvil\n(reporte de posición)" as appMovil
}

node "Servicios de notificación" as nNotif {
 artifact "Email / SMS / WhatsApp" as canales
}

node "Servidor Donaciones" as nDonaciones {
 artifact "tpa-donaciones.jar\nJava 17 + Javalin + JPA/Hibernate\n:8080" as donaciones
}

node "Servidor Logística" as nLogistica {
 artifact "tpa-logistica.jar\nJava 17 + Javalin + JPA/Hibernate\n:8081" as logistica
}

node "Proveedor externo" as nPlanif {
 artifact "Planificador de Rutas\n:8082" as planificador
}

node "Servidor de Base de Datos" as nDb {
 node "PostgreSQL 16 :5432" {
  database "donatrack_donaciones" as dbDonaciones
  database "donatrack_logistica" as dbLogistica
 }
}

csv      -down-> donaciones : HTTPS\n(importación CSV)
browser  -down-> logistica  : HTTPS\n(dashboard)
appMovil -down-> logistica  : HTTPS\n(posición GPS)

logistica -left-> donaciones : HTTP/REST\n(donaciones asignadas\n+ eventos de entrega)
donaciones -left-> canales   : notificaciones

logistica -right-> planificador : HTTP async\n(lotes ≤100)
planificador ..> logistica      : callback

donaciones -down-> dbDonaciones : JDBC
logistica  -down-> dbLogistica  : JDBC

@enduml
